### PR TITLE
Remove blockHeight from Block struct.

### LINKED ISSUE #16: The `Block` type should not have an indpendent block height
The block height is part of the block header in Decred, so there should not be a separate field on the Block type itself for tracking that information.  This means the `blockHeight int64` and associated code should be removed.

If it is desirable to keep the existing `Height` and `SetHeight` functions, they should be returning and updating the `b.msgBlock.Header.Height` field accordingly.

### PR DESCRIPTION
**Pull request by dajohi**
The block height is part of the block header in Decred, so there
is no need to track it.

Requires https://github.com/decred/dcrd/pull/471
Fixes #16

### CODE REVIEW

**Comment by dajohi** [comment]
I am of the opinion SetHeight should be removed as well.  I do not see a need for it.

**Comment by davecgh** [comment]
This is failing Travis.

**Comment by davecgh** [comment]
I agree regarding the removal of `SetHeight`.  Both of those were important in Bitcoin because the block header does not have the height in it, however that is not the case with Decred.

**Comment by jrick** [comment]
Failing travis because this is trying to build everything in dcrd.  Travis needs to only test building `$(glide nv)`.

**Pull request merged**
