### PR TITLE
Remove the defaultNet param for DecodeAddress

### PR DESCRIPTION
**Pull request by dnldd**
~~NOTE: This PR contains a temporary glide redirect to https://github.com/dnldd/dcrd/tree/decodeaddress.  This will need to be removed before merging~~

### CODE REVIEW

**Comment by davecgh** [comment]
Concept ACK.

This is a holdover from Bitcoin where raw public keys were allowed and thus there was no way to decode a network.  Decred resolved this by ensuring that pay-to-pubkey style addresses do encode the network and include a checksum as well.  Thus, there is no longer any reason to have a default network parameter.

**Comment by davecgh** [comment]
Please make sure the commit messages conform to the [Model Git Commit Messages](https://github.com/decred/dcrd/blob/master/docs/code_contribution_guidelines.md#ModelGitCommitMessages) section of the [Code Contribution Guidelines](https://github.com/decred/dcrd/blob/master/docs/code_contribution_guidelines.md).

**Comment by davecgh** [comment]
Reopening this since there is no need to close it.  All you need to do is rebase and correct the commit message.

**Comment by dnldd** [comment]
**NOTE: This PR contains a temporary glide redirect to https://github.com/dnldd/dcrd/tree/decodeaddress.  This will need to be removed before merging**

**Pull request merged**
